/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package boundary.PatientManagementUI;

import boundary.MainFrame;
import utility.ImageUtils;

/**
 *
 * @author szepi
 */
public class PatientManagementPanel extends javax.swing.JPanel {

    private MainFrame mainFrame;
    
    /**
     * Creates new form PatientManagementPanel
     */
    public PatientManagementPanel(MainFrame mainFrame) {
        this.mainFrame = mainFrame;
        initComponents();
        logoLabel = ImageUtils.getImageLabel("tarumt_logo.png", logoLabel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoLabel = new javax.swing.JLabel();
        titlePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        buttonWrapperPanel = new javax.swing.JPanel();
        buttonWrapper = new javax.swing.JPanel();
        buttonPanel = new javax.swing.JPanel();
        PatientManagement = new javax.swing.JButton();
        PatientQueue = new javax.swing.JButton();
        MainMenu = new javax.swing.JButton();
        Exit = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());
        add(logoLabel, java.awt.BorderLayout.PAGE_START);

        titlePanel.setLayout(new java.awt.BorderLayout());

        titleLabel.setFont(new java.awt.Font("Corbel", 1, 36)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Patient Management Menu");
        titleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlePanel.add(titleLabel, java.awt.BorderLayout.PAGE_START);

        buttonWrapperPanel.setLayout(new java.awt.BorderLayout());

        buttonPanel.setLayout(new java.awt.GridLayout(3, 2, 50, 50));

        PatientManagement.setText("Patient Management");
        PatientManagement.setPreferredSize(new java.awt.Dimension(200, 50));
        PatientManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientManagementActionPerformed(evt);
            }
        });
        buttonPanel.add(PatientManagement);

        PatientQueue.setText("Patient Queue");
        PatientQueue.setPreferredSize(new java.awt.Dimension(200, 50));
        PatientQueue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientQueueActionPerformed(evt);
            }
        });
        buttonPanel.add(PatientQueue);

        MainMenu.setText("Main Menu");
        MainMenu.setPreferredSize(new java.awt.Dimension(200, 50));
        MainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainMenuActionPerformed(evt);
            }
        });
        buttonPanel.add(MainMenu);

        Exit.setText("Exit");
        Exit.setPreferredSize(new java.awt.Dimension(200, 50));
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        buttonPanel.add(Exit);

        buttonWrapper.add(buttonPanel);

        buttonWrapperPanel.add(buttonWrapper, java.awt.BorderLayout.CENTER);

        titlePanel.add(buttonWrapperPanel, java.awt.BorderLayout.CENTER);

        add(titlePanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void PatientManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientManagementActionPerformed
        mainFrame.showPanel("patientRegistration");
    }//GEN-LAST:event_PatientManagementActionPerformed

    private void PatientQueueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientQueueActionPerformed
        mainFrame.showPanel("queueManagement");
    }//GEN-LAST:event_PatientQueueActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
       mainFrame.dispose();
    }//GEN-LAST:event_ExitActionPerformed

    private void MainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainMenuActionPerformed
        mainFrame.showPanel("clinicMenu");
    }//GEN-LAST:event_MainMenuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JButton MainMenu;
    private javax.swing.JButton PatientManagement;
    private javax.swing.JButton PatientQueue;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel buttonWrapper;
    private javax.swing.JPanel buttonWrapperPanel;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables
}
