/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package boundary.PatientManagementUI;

import adt.DoublyLinkedList;
import adt.Node;
import boundary.MainFrame;
import enitity.Patient;
import enitity.QueueEntry;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utility.ImageUtils;
import utility.ReportGenerator;

/**
 *
 * @author szepi
 */
public class QueueManagementPanel extends javax.swing.JPanel {

     private MainFrame mainFrame;
     private DoublyLinkedList<QueueEntry> queueList = new DoublyLinkedList<>();
    /**
     * Creates new form QueueManagementPanel
     */
    public QueueManagementPanel(MainFrame mainFrame) {
         this.mainFrame = mainFrame;
        initComponents();
        
        logoLabel = ImageUtils.getImageLabel("tarumt_logo.png", logoLabel);
        loadQueueData();
        displayQueueData();
    }

    private int lastNumber = 1000; // starting number

    private String generateQueueNumber() {
    lastNumber++;
    return "E" + lastNumber;
    }
    
    private void loadQueueData() {
    DoublyLinkedList<QueueEntry> savedQueue =
        (DoublyLinkedList<QueueEntry>) utility.FileUtils.readDataFromFile("queue");

    if (savedQueue != null) {
        queueList = savedQueue;
    } else {
        queueList = new DoublyLinkedList<>();
    }
}


    
    private void saveQueueData() {
    utility.FileUtils.writeDataToFile("queue", queueList);
}
    
private void displayQueueData() {
    DefaultTableModel model = (DefaultTableModel) queueTable.getModel();

    // Clear existing table data
    model.setRowCount(0);

    // Set column identifiers if not already set
    if (model.getColumnCount() == 0) {
        model.setColumnIdentifiers(new String[] {
            "Patient ID", "Patient Name", "IC No", 
            "Queue No", "Status", 
            "Enqueue Time", "Start Time",
            "Waiting Time"
        });
    }

    // Loop through queueList and add rows to the table
    for (QueueEntry entry : queueList) {
        Patient patient = entry.getPatient();
        model.addRow(new Object[] {
            patient.getPatientID(),
            patient.getPatientName(),
            patient.getPatientIC(),
            entry.getQueueNumber(),
            entry.getStatus(),
            entry.getFormattedEnqueueTime(),
            entry.getFormattedStartTime(),
            entry.getFormattedWaitingTime()
        });
    }
}




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoLabel = new javax.swing.JLabel();
        titlePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        searchWrapperPanel = new javax.swing.JPanel();
        searchPanel = new javax.swing.JPanel();
        filterLabel = new javax.swing.JLabel();
        filterBox = new javax.swing.JComboBox<>();
        filterField = new javax.swing.JTextField();
        queueTablePanel = new javax.swing.JScrollPane();
        queueTable = new javax.swing.JTable();
        ButtonPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());
        add(logoLabel, java.awt.BorderLayout.PAGE_START);

        titlePanel.setLayout(new java.awt.BorderLayout());

        titleLabel.setFont(new java.awt.Font("Corbel", 1, 36)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Queue Management");
        titleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlePanel.add(titleLabel, java.awt.BorderLayout.PAGE_START);

        searchWrapperPanel.setLayout(new java.awt.BorderLayout());

        filterLabel.setText("Filter By :");
        searchPanel.add(filterLabel);

        filterBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Queue No", "Status", " " }));
        filterBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterBoxActionPerformed(evt);
            }
        });
        searchPanel.add(filterBox);

        filterField.setColumns(15);
        filterField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterFieldActionPerformed(evt);
            }
        });
        searchPanel.add(filterField);

        searchWrapperPanel.add(searchPanel, java.awt.BorderLayout.PAGE_START);

        queueTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        queueTablePanel.setViewportView(queueTable);

        searchWrapperPanel.add(queueTablePanel, java.awt.BorderLayout.CENTER);

        jButton1.setText("Add Patient Queue");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        ButtonPanel.add(jButton1);

        jButton3.setText("Generate Report");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        ButtonPanel.add(jButton3);

        jButton2.setText("Done");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        ButtonPanel.add(jButton2);

        searchWrapperPanel.add(ButtonPanel, java.awt.BorderLayout.PAGE_END);

        titlePanel.add(searchWrapperPanel, java.awt.BorderLayout.CENTER);

        add(titlePanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void filterFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filterFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       QueueDialog dialog = new QueueDialog(mainFrame, true);
dialog.setLocationRelativeTo(this);
dialog.setVisible(true);

Patient selectedPatient = dialog.getResult();

if (selectedPatient != null) {
    String queueNo = generateQueueNumber();
    String status = "Waiting";

    // Create QueueEntry object
    QueueEntry entry = new QueueEntry(selectedPatient, queueNo, status);
    queueList.insertLast(entry);
    saveQueueData(); // save to file

    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) queueTable.getModel();
    if (model.getColumnCount() == 0) {
        model.setColumnIdentifiers(new String[] {
            "Patient ID", "Patient Name", "IC No", "Queue No", "Status"
        });
    }

    model.addRow(new Object[] {
        selectedPatient.getPatientID(),
        selectedPatient.getPatientName(),
        selectedPatient.getPatientIC(),
        queueNo,
        status
    });
}

    }//GEN-LAST:event_jButton1ActionPerformed

    private void filterBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filterBoxActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        saveQueueData();
        mainFrame.showPanel("patientManagement");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ReportGenerator.generateQueueStatisticsReport(queueList);
         JOptionPane.showMessageDialog(this, "Queue Statistics Report generated successfully!");
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonPanel;
    private javax.swing.JComboBox<String> filterBox;
    private javax.swing.JTextField filterField;
    private javax.swing.JLabel filterLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JTable queueTable;
    private javax.swing.JScrollPane queueTablePanel;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JPanel searchWrapperPanel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables
}
