/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package boundary.PatientManagementUI;

import adt.DoublyLinkedList;
import enitity.Patient;
import enitity.QueueEntry;
import javax.swing.JOptionPane;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;


/**
 *
 * @author szepi
 */
public class QueueDialog extends javax.swing.JDialog {

    private Patient result;
    private DoublyLinkedList<Patient> patientList = new DoublyLinkedList<>();
    /**
     * Creates new form QueueDialog
     */
    public QueueDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        ICNoInput.setText("");
        setICFieldLimit(); 
        
        
    }
    
     private void setICFieldLimit() {
        ((AbstractDocument) ICNoInput.getDocument())
            .setDocumentFilter(new DocumentFilter() {
                @Override
                public void insertString(FilterBypass fb, int offset, String string,
                                         AttributeSet attr) throws BadLocationException {
                    if ((fb.getDocument().getLength() + string.length()) <= 14) {
                        super.insertString(fb, offset, string, attr);
                    }
                }
                @Override
                public void replace(FilterBypass fb, int offset, int length, String text,
                                    AttributeSet attrs) throws BadLocationException {
                    if ((fb.getDocument().getLength() - length + text.length()) <= 14) {
                        super.replace(fb, offset, length, text, attrs);
                    }
                }
            });
    }
    
    
    
 private void savePatientAction(java.awt.event.ActionEvent evt) {
    String icNumber = ICNoInput.getText().trim();
    if (icNumber.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter IC Number");
        return;
    }

    DoublyLinkedList<Patient> patients =
        (DoublyLinkedList<Patient>) utility.FileUtils.readDataFromFile("patients");
    Patient foundPatient = null;

    for (Patient p : patients) {
        if (p.getPatientIC().equalsIgnoreCase(icNumber)) {
            foundPatient = p;
            break;
        }
    }

    if (foundPatient != null) {
        this.result = foundPatient; // store the whole patient
        this.dispose(); // close dialog
    } else {
        JOptionPane.showMessageDialog(this, "No patient found with IC: " + icNumber,
                                      "Error", JOptionPane.ERROR_MESSAGE);
    }
}

    
    public Patient getResult() {
    return result;
}
  
  
      

    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoPanel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        titlePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        formWrapperPanel = new javax.swing.JPanel();
        formGridPanel = new javax.swing.JPanel();
        ICNoInputLabel = new javax.swing.JLabel();
        ICNoInput = new javax.swing.JTextField();
        buttonPanel = new javax.swing.JPanel();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        logoPanel.setLayout(new java.awt.BorderLayout());
        logoPanel.add(logoLabel, java.awt.BorderLayout.PAGE_START);

        titlePanel.setLayout(new java.awt.BorderLayout());

        titleLabel.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Queue Management");
        titleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlePanel.add(titleLabel, java.awt.BorderLayout.PAGE_START);

        formWrapperPanel.setPreferredSize(new java.awt.Dimension(313, 283));

        formGridPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        formGridPanel.setAlignmentX(1.0F);
        formGridPanel.setAlignmentY(1.0F);
        formGridPanel.setLayout(new java.awt.GridLayout());

        ICNoInputLabel.setText("IC Number :");
        formGridPanel.add(ICNoInputLabel);

        ICNoInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ICNoInputActionPerformed(evt);
            }
        });
        formGridPanel.add(ICNoInput);

        formWrapperPanel.add(formGridPanel);

        titlePanel.add(formWrapperPanel, java.awt.BorderLayout.CENTER);

        logoPanel.add(titlePanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(logoPanel, java.awt.BorderLayout.CENTER);

        buttonPanel.setPreferredSize(new java.awt.Dimension(627, 100));

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(saveButton)
                .addGap(45, 45, 45)
                .addComponent(cancelButton)
                .addContainerGap(216, Short.MAX_VALUE))
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(cancelButton))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        getContentPane().add(buttonPanel, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ICNoInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ICNoInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ICNoInputActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        savePatientAction(evt);
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.result = null; // Set result to null to indicate cancellation
        this.dispose(); // Close the dialog
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QueueDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QueueDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QueueDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QueueDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QueueDialog dialog = new QueueDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ICNoInput;
    private javax.swing.JLabel ICNoInputLabel;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel formGridPanel;
    private javax.swing.JPanel formWrapperPanel;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables
}
