/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package boundary.DoctorManagementUI;

import adt.DoublyLinkedList;
import adt.Pair;
import enitity.Doctor;
import javax.swing.JOptionPane;
import utility.ImageUtils;

/**
 *
 * @author Chok Chun Fai
 */
public class DoctorDialog extends javax.swing.JDialog {

    // This variable will hold the new doctor if "Save" is clicked.
    private Pair<String, Doctor> result = null;
    private int lastDocIndex = Doctor.getDoctorIndex();
    Doctor newDoctor = new Doctor();

    /**
     * Creates new form DoctorDialog
     *
     * @param parent
     * @param modal
     */
    public DoctorDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        logoLabel = ImageUtils.getImageLabel("tarumt_logo.png", logoLabel);
        formDocIDfield.setText(newDoctor.getDoctorID());
        DoublyLinkedList<String> position = new DoublyLinkedList<>();
        position.insertLast("Consultation");
        position.insertLast("Doctor");
        position.insertLast("Internship");
        for (String i : position) {
            formPositionBox.addItem(i);
        }
        this.setLocationRelativeTo(parent);
    }

    /**
     * A public method for the main panel to call to get the result. Returns
     * null if the user clicked "Cancel".
     *
     * @return
     */
    public Pair<String, Doctor> getResult() {
        return result;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoPanel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        titlePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        formWrapperPanel = new javax.swing.JPanel();
        formGridPanel = new javax.swing.JPanel();
        formDocIDlabel = new javax.swing.JLabel();
        formDocIDfield = new javax.swing.JTextField();
        formNameLabel = new javax.swing.JLabel();
        formNameInput = new javax.swing.JTextField();
        formAgeLabel = new javax.swing.JLabel();
        formAgeInput = new javax.swing.JTextField();
        formPhoneLabel = new javax.swing.JLabel();
        formPhoneInput = new javax.swing.JTextField();
        formPositionLabel = new javax.swing.JLabel();
        formPositionBox = new javax.swing.JComboBox<>();
        buttonPanel = new javax.swing.JPanel();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 500));
        setPreferredSize(new java.awt.Dimension(600, 500));

        logoPanel.setLayout(new java.awt.BorderLayout());
        logoPanel.add(logoLabel, java.awt.BorderLayout.CENTER);

        titlePanel.setLayout(new java.awt.BorderLayout());

        titleLabel.setFont(new java.awt.Font("Corbel", 1, 36)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("New Application Form");
        titleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlePanel.add(titleLabel, java.awt.BorderLayout.PAGE_START);

        formGridPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Doctor Information :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Corbel", 1, 14))); // NOI18N
        formGridPanel.setMinimumSize(new java.awt.Dimension(350, 228));
        formGridPanel.setPreferredSize(new java.awt.Dimension(300, 228));
        formGridPanel.setLayout(new java.awt.GridLayout(5, 2, 5, 15));

        formDocIDlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formDocIDlabel.setText("ID :");
        formGridPanel.add(formDocIDlabel);

        formDocIDfield.setEditable(false);
        formDocIDfield.setColumns(15);
        formGridPanel.add(formDocIDfield);

        formNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formNameLabel.setText("Name :");
        formGridPanel.add(formNameLabel);

        formNameInput.setColumns(15);
        formGridPanel.add(formNameInput);

        formAgeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formAgeLabel.setText("Age :");
        formGridPanel.add(formAgeLabel);

        formAgeInput.setColumns(15);
        formGridPanel.add(formAgeInput);

        formPhoneLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formPhoneLabel.setText("Phone :");
        formGridPanel.add(formPhoneLabel);

        formPhoneInput.setColumns(15);
        formGridPanel.add(formPhoneInput);

        formPositionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formPositionLabel.setText("Position :");
        formGridPanel.add(formPositionLabel);

        formPositionBox.setPreferredSize(new java.awt.Dimension(100, 29));
        formGridPanel.add(formPositionBox);

        formWrapperPanel.add(formGridPanel);

        titlePanel.add(formWrapperPanel, java.awt.BorderLayout.CENTER);

        logoPanel.add(titlePanel, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(logoPanel, java.awt.BorderLayout.PAGE_START);

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(saveButton);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(cancelButton);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // Basic validation
        if (formNameInput.getText().trim().isEmpty() || formAgeInput.getText().trim().isEmpty() || formPhoneInput.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Field cannot be empty.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {

            // 1. Get all data from the form fields
            String name = formNameInput.getText().trim();
            int age = Integer.parseInt(formAgeInput.getText());
            String phone = formPhoneInput.getText().trim();
            String position = (String) formPositionBox.getSelectedItem();

            // 2. Create the new objects
            newDoctor.setName(name);
            newDoctor.setAge(age);
            newDoctor.setPhoneNumber(phone);
            newDoctor.setPosition(position);
            newDoctor.setStatus("Present");

            // 3. Store the result and close the dialog
            this.result = new Pair<>(newDoctor.getDoctorID(), newDoctor);
            this.dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please check your input values.", "Input Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.result = null;
        Doctor.setDoctorIndex(lastDocIndex);
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DoctorDialog dialog = new DoctorDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField formAgeInput;
    private javax.swing.JLabel formAgeLabel;
    private javax.swing.JTextField formDocIDfield;
    private javax.swing.JLabel formDocIDlabel;
    private javax.swing.JPanel formGridPanel;
    private javax.swing.JTextField formNameInput;
    private javax.swing.JLabel formNameLabel;
    private javax.swing.JTextField formPhoneInput;
    private javax.swing.JLabel formPhoneLabel;
    private javax.swing.JComboBox<String> formPositionBox;
    private javax.swing.JLabel formPositionLabel;
    private javax.swing.JPanel formWrapperPanel;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables
}
