/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package boundary.DoctorManagementUI;

import adt.DoublyLinkedList;
import adt.Pair;
import control.DoctorManagementController.DoctorEditControl;
import enitity.Doctor;
import java.awt.Frame;
import utility.ImageUtils;

/**
 *
 * @author Chok Chun Fai
 */
public class DoctorEditDialog extends javax.swing.JDialog {

    private final DoctorEditControl control;

    /**
     *
     * @param parent
     * @param modal
     * @param masterDoctorList
     */
    public DoctorEditDialog(Frame parent, boolean modal, DoublyLinkedList<Pair<String, Doctor>> masterDoctorList) {
        super(parent, modal);
        initComponents();
        logoLabel = ImageUtils.getImageLabel("tarumt_logo.png", logoLabel);

        // Initialize the controller
        this.control = new DoctorEditControl(this, masterDoctorList);

        // Setup UI components like the position combo box
        setupComponents();

        this.setLocationRelativeTo(parent);
    }

    private void setupComponents() {
        // This is static data, so it can remain in the view
        formPositionBox.addItem("Consultant");
        formPositionBox.addItem("Doctor");
        formPositionBox.addItem("Internship");

        formStatusBox.addItem("Present");
        formStatusBox.addItem("Absent");
        formStatusBox.addItem("Resigned");

        setFieldsEditable(false);
    }

    public void displayDoctorInfo(String id, Doctor doc) {
        formDocIDfield.setText(id);
        formNameInput.setText(doc.getName());
        formAgeInput.setText(String.valueOf(doc.getAge()));
        formPhoneInput.setText(doc.getPhoneNumber());
        formPositionBox.setSelectedItem(doc.getPosition());
    }

    public void clearForm() {
        formDocIDfield.setText("");
        formNameInput.setText("");
        formAgeInput.setText("");
        formPhoneInput.setText("");
        formPositionBox.setSelectedIndex(0);
    }

    public void setFieldsEditable(boolean editable) {
        formDocIDfield.setEnabled(editable);
        formNameInput.setEnabled(editable);
        formAgeInput.setEnabled(editable);
        formPhoneInput.setEnabled(editable);
        formPositionBox.setEnabled(editable);
        formPositionBox.setEnabled(editable);
        formStatusBox.setEnabled(editable);
        saveButton.setEnabled(editable);
    }

    // Getters for the controller to retrieve form data
    public String getDoctorName() {
        return formNameInput.getText();
    }

    public int getDoctorAge() {
        return Integer.parseInt(formAgeInput.getText());
    }

    public String getDoctorPhone() {
        return formPhoneInput.getText();
    }

    public String getDoctorPosition() {
        return (String) formPositionBox.getSelectedItem();
    }

    public String getDoctorStatus() {
        return (String) formStatusBox.getSelectedItem();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoPanel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        titlePanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        searchTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        formWrapperPanel = new javax.swing.JPanel();
        formGridPanel = new javax.swing.JPanel();
        formDocIDlabel = new javax.swing.JLabel();
        formDocIDfield = new javax.swing.JTextField();
        formNameLabel = new javax.swing.JLabel();
        formNameInput = new javax.swing.JTextField();
        formAgeLabel = new javax.swing.JLabel();
        formAgeInput = new javax.swing.JTextField();
        formPhoneLabel = new javax.swing.JLabel();
        formPhoneInput = new javax.swing.JTextField();
        formPositionLabel = new javax.swing.JLabel();
        formPositionBox = new javax.swing.JComboBox<>();
        formStatusLabel = new javax.swing.JLabel();
        formStatusBox = new javax.swing.JComboBox<>();
        buttonPanel = new javax.swing.JPanel();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 500));

        logoPanel.setLayout(new java.awt.BorderLayout());
        logoPanel.add(logoLabel, java.awt.BorderLayout.CENTER);

        titlePanel.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Search ID to Edit :");
        jPanel2.add(jLabel1);

        searchTextField.setColumns(15);
        searchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextFieldActionPerformed(evt);
            }
        });
        jPanel2.add(searchTextField);

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        jPanel2.add(searchButton);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        formGridPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Doctor Information :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Corbel", 1, 14))); // NOI18N
        formGridPanel.setMinimumSize(new java.awt.Dimension(350, 228));
        formGridPanel.setPreferredSize(new java.awt.Dimension(300, 270));
        formGridPanel.setLayout(new java.awt.GridLayout(6, 2, 5, 15));

        formDocIDlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formDocIDlabel.setText("ID :");
        formGridPanel.add(formDocIDlabel);

        formDocIDfield.setEditable(false);
        formDocIDfield.setColumns(15);
        formGridPanel.add(formDocIDfield);

        formNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formNameLabel.setText("Name :");
        formGridPanel.add(formNameLabel);

        formNameInput.setColumns(15);
        formGridPanel.add(formNameInput);

        formAgeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formAgeLabel.setText("Age :");
        formGridPanel.add(formAgeLabel);

        formAgeInput.setColumns(15);
        formGridPanel.add(formAgeInput);

        formPhoneLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formPhoneLabel.setText("Phone :");
        formGridPanel.add(formPhoneLabel);

        formPhoneInput.setColumns(15);
        formGridPanel.add(formPhoneInput);

        formPositionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formPositionLabel.setText("Position :");
        formGridPanel.add(formPositionLabel);

        formPositionBox.setPreferredSize(new java.awt.Dimension(100, 29));
        formGridPanel.add(formPositionBox);

        formStatusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formStatusLabel.setText("Status :");
        formGridPanel.add(formStatusLabel);

        formStatusBox.setPreferredSize(new java.awt.Dimension(100, 29));
        formGridPanel.add(formStatusBox);

        formWrapperPanel.add(formGridPanel);

        jPanel1.add(formWrapperPanel, java.awt.BorderLayout.CENTER);

        titlePanel.add(jPanel1, java.awt.BorderLayout.CENTER);

        logoPanel.add(titlePanel, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(logoPanel, java.awt.BorderLayout.PAGE_START);

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(saveButton);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(cancelButton);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.PAGE_END);
        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        control.saveDoctorChanges();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose(); // Simply close the dialog
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        control.searchDoctorById(searchTextField.getText());
    }//GEN-LAST:event_searchButtonActionPerformed

    private void searchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField formAgeInput;
    private javax.swing.JLabel formAgeLabel;
    private javax.swing.JTextField formDocIDfield;
    private javax.swing.JLabel formDocIDlabel;
    private javax.swing.JPanel formGridPanel;
    private javax.swing.JTextField formNameInput;
    private javax.swing.JLabel formNameLabel;
    private javax.swing.JTextField formPhoneInput;
    private javax.swing.JLabel formPhoneLabel;
    private javax.swing.JComboBox<String> formPositionBox;
    private javax.swing.JLabel formPositionLabel;
    private javax.swing.JComboBox<String> formStatusBox;
    private javax.swing.JLabel formStatusLabel;
    private javax.swing.JPanel formWrapperPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables
}
