package boundary.DoctorManagementUI;

import adt.Pair;
import control.DoctorManagementController.DoctorAddControl; // Import the controller
import enitity.Doctor;
import java.awt.Frame;
import utility.ImageUtils;

public class DoctorAddDialog extends javax.swing.JDialog {

    private final DoctorAddControl control;
    private Pair<String, Doctor> result = null; // To hold the final result

    public DoctorAddDialog(Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        logoLabel = ImageUtils.getImageLabel("tarumt_logo.png", logoLabel);

        // The controller is created when the dialog is created
        this.control = new DoctorAddControl(this);

        setupComponents();
        this.setLocationRelativeTo(parent);
    }

    private void setupComponents() {
        // Populate the position dropdown
        formPositionBox.addItem("Consultant");
        formPositionBox.addItem("Doctor");
        formPositionBox.addItem("Internship");
    }

    public Pair<String, Doctor> getResult() {
        return result;
    }

    public void setResultAndClose(Pair<String, Doctor> result) {
        this.result = result;
        this.dispose();
    }

    // Getters for the controller to access form data
    public void setDoctorId(String id) {
        formDocIDfield.setText(id);
    }

    public String getDoctorName() {
        return formNameInput.getText();
    }

    public String getDoctorAge() {
        return formAgeInput.getText();
    }

    public String getDoctorPhone() {
        return formPhoneInput.getText();
    }

    public String getDoctorPosition() {
        return (String) formPositionBox.getSelectedItem();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoPanel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        titlePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        formWrapperPanel = new javax.swing.JPanel();
        formGridPanel = new javax.swing.JPanel();
        formDocIDlabel = new javax.swing.JLabel();
        formDocIDfield = new javax.swing.JTextField();
        formNameLabel = new javax.swing.JLabel();
        formNameInput = new javax.swing.JTextField();
        formAgeLabel = new javax.swing.JLabel();
        formAgeInput = new javax.swing.JTextField();
        formPhoneLabel = new javax.swing.JLabel();
        formPhoneInput = new javax.swing.JTextField();
        formPositionLabel = new javax.swing.JLabel();
        formPositionBox = new javax.swing.JComboBox<>();
        buttonPanel = new javax.swing.JPanel();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 500));

        logoPanel.setLayout(new java.awt.BorderLayout());
        logoPanel.add(logoLabel, java.awt.BorderLayout.CENTER);

        titlePanel.setLayout(new java.awt.BorderLayout());

        titleLabel.setFont(new java.awt.Font("Corbel", 1, 36)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("New Application Form");
        titleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlePanel.add(titleLabel, java.awt.BorderLayout.PAGE_START);

        formGridPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Doctor Information :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Corbel", 1, 14))); // NOI18N
        formGridPanel.setMinimumSize(new java.awt.Dimension(350, 228));
        formGridPanel.setPreferredSize(new java.awt.Dimension(300, 228));
        formGridPanel.setLayout(new java.awt.GridLayout(5, 2, 5, 15));

        formDocIDlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formDocIDlabel.setText("ID :");
        formGridPanel.add(formDocIDlabel);

        formDocIDfield.setEditable(false);
        formDocIDfield.setColumns(15);
        formGridPanel.add(formDocIDfield);

        formNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formNameLabel.setText("Name :");
        formGridPanel.add(formNameLabel);

        formNameInput.setColumns(15);
        formGridPanel.add(formNameInput);

        formAgeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formAgeLabel.setText("Age :");
        formGridPanel.add(formAgeLabel);

        formAgeInput.setColumns(15);
        formGridPanel.add(formAgeInput);

        formPhoneLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formPhoneLabel.setText("Phone :");
        formGridPanel.add(formPhoneLabel);

        formPhoneInput.setColumns(15);
        formGridPanel.add(formPhoneInput);

        formPositionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formPositionLabel.setText("Position :");
        formGridPanel.add(formPositionLabel);

        formPositionBox.setPreferredSize(new java.awt.Dimension(100, 29));
        formGridPanel.add(formPositionBox);

        formWrapperPanel.add(formGridPanel);

        titlePanel.add(formWrapperPanel, java.awt.BorderLayout.CENTER);

        logoPanel.add(titlePanel, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(logoPanel, java.awt.BorderLayout.PAGE_START);

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(saveButton);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(cancelButton);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        control.saveNewDoctor();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        control.cancelAdd();
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorAddDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorAddDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorAddDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorAddDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DoctorAddDialog dialog = new DoctorAddDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField formAgeInput;
    private javax.swing.JLabel formAgeLabel;
    private javax.swing.JTextField formDocIDfield;
    private javax.swing.JLabel formDocIDlabel;
    private javax.swing.JPanel formGridPanel;
    private javax.swing.JTextField formNameInput;
    private javax.swing.JLabel formNameLabel;
    private javax.swing.JTextField formPhoneInput;
    private javax.swing.JLabel formPhoneLabel;
    private javax.swing.JComboBox<String> formPositionBox;
    private javax.swing.JLabel formPositionLabel;
    private javax.swing.JPanel formWrapperPanel;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables
}
