package boundary;

import boundary.DoctorManagementUI.DoctorInformationPanel;
import boundary.DoctorManagementUI.DoctorManagementPanel;
import boundary.DoctorManagementUI.DoctorSchedulePanel;
import boundary.PharmacyManagementUI.PharmacyManagementPanel;
import java.awt.CardLayout;

/**
 *
 * @author Chok Chun Fai
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();

        /* Create instances of multiple screen panels
        *  Pass 'this' Main Frame 
         */
        ClinicMenuPanel clinicPanel = new ClinicMenuPanel(this);
        DoctorManagementPanel docPanel = new DoctorManagementPanel(this);
        DoctorInformationPanel docInfoPanel = new DoctorInformationPanel(this);
        DoctorSchedulePanel docSchedulePanel = new DoctorSchedulePanel(this);
        
        PharmacyManagementPanel pharPanel = new PharmacyManagementPanel(this);

        // Add the panels to the cardPanel with unique names
        cardPanel.add(clinicPanel, "clinicMenu");
        cardPanel.add(docPanel, "doctorManagement");
        cardPanel.add(docInfoPanel, "doctorInformation");
        cardPanel.add(docSchedulePanel, "doctorSchedule");
        
        cardPanel.add(pharPanel, "pharmacyManagement");

        // Set frame properties
        this.setTitle("Clinic Management System");
        this.pack();
        this.setLocationRelativeTo(null);
    }

    // Function to switch different windows
    public void showPanel(String panelName) {
        CardLayout cl = (CardLayout) (cardPanel.getLayout());
        cl.show(cardPanel, panelName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cardPanel.setMaximumSize(new java.awt.Dimension(700, 500));
        cardPanel.setMinimumSize(new java.awt.Dimension(700, 500));
        cardPanel.setName(""); // NOI18N
        cardPanel.setPreferredSize(new java.awt.Dimension(700, 500));
        cardPanel.setLayout(new java.awt.CardLayout());
        getContentPane().add(cardPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cardPanel;
    // End of variables declaration//GEN-END:variables
}