/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package boundary.ConsultationManagementUI;

import boundary.MainFrame;
import utility.ImageUtils;
// no imports required; using fully-qualified names in generated code

/**
 * Main Consultation Management Panel
 * @author Zhen Bang
 */
public class ConsultationManagementPanel extends javax.swing.JPanel {

    private MainFrame mainFrame;
    // Component variables are managed in the guarded block below
    
    /**
     * Creates new form ConsultationManagementPanel
     */
    public ConsultationManagementPanel(MainFrame mainFrame) {
        this.mainFrame = mainFrame;
        initComponents();
        // Apply logo image like other modules
        logoLabel = ImageUtils.getImageLabel("tarumt_logo.png", logoLabel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoLabel = new javax.swing.JLabel();
        titlePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        buttonWrapperPanel = new javax.swing.JPanel();
        buttonWrapper = new javax.swing.JPanel();
        buttonPanel = new javax.swing.JPanel();
        consultationButton = new javax.swing.JButton();
        appointmentButton = new javax.swing.JButton();
        queueButton = new javax.swing.JButton();
        reportsButton = new javax.swing.JButton();
        prescriptionButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());
        add(logoLabel, java.awt.BorderLayout.PAGE_START);

        titlePanel.setLayout(new java.awt.BorderLayout());

        titleLabel.setFont(new java.awt.Font("Corbel", 1, 36)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText(" Consultation Management Menu");
        titleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlePanel.add(titleLabel, java.awt.BorderLayout.PAGE_START);

        buttonWrapperPanel.setLayout(new java.awt.BorderLayout());

        buttonPanel.setMinimumSize(new java.awt.Dimension(1000, 800));
        buttonPanel.setLayout(new java.awt.GridLayout(3, 2, 50, 50));

        consultationButton.setText("Manage Consultations");
        consultationButton.setPreferredSize(new java.awt.Dimension(200, 50));
        consultationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultationButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(consultationButton);

        appointmentButton.setText("Manage Appointments");
        appointmentButton.setPreferredSize(new java.awt.Dimension(200, 50));
        appointmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appointmentButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(appointmentButton);

        queueButton.setText("Patient Queue");
        queueButton.setPreferredSize(new java.awt.Dimension(200, 50));
        queueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                queueButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(queueButton);

        reportsButton.setText("Generate Reports");
        reportsButton.setPreferredSize(new java.awt.Dimension(200, 50));
        reportsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportsButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(reportsButton);

        prescriptionButton.setText("Manage Prescriptions");
        prescriptionButton.setPreferredSize(new java.awt.Dimension(200, 50));
        prescriptionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prescriptionButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(prescriptionButton);

        backButton.setText("Main Menu");
        backButton.setPreferredSize(new java.awt.Dimension(200, 50));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(backButton);

        buttonWrapper.add(buttonPanel);

        buttonWrapperPanel.add(buttonWrapper, java.awt.BorderLayout.CENTER);

        titlePanel.add(buttonWrapperPanel, java.awt.BorderLayout.CENTER);

        add(titlePanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void consultationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultationButtonActionPerformed
        // Refresh the consultation panel display before showing it
        mainFrame.getConsultationPanel().refreshConsultationDisplay();
        mainFrame.showPanel("consultationPanel");
    }//GEN-LAST:event_consultationButtonActionPerformed

    private void appointmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appointmentButtonActionPerformed
        mainFrame.showPanel("appointmentPanel");
    }//GEN-LAST:event_appointmentButtonActionPerformed

    private void prescriptionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prescriptionButtonActionPerformed
        mainFrame.getPrescriptionPanel().reloadPrescriptionData();
        mainFrame.showPanel("prescriptionPanel");
    }//GEN-LAST:event_prescriptionButtonActionPerformed

    private void queueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_queueButtonActionPerformed
        // Refresh the consultation queue from shared patient queue before showing
        mainFrame.getQueuePanel().refreshQueueDisplay();
        mainFrame.showPanel("queuePanel");
    }//GEN-LAST:event_queueButtonActionPerformed

    private void reportsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportsButtonActionPerformed
        mainFrame.showPanel("consultationReports");
    }//GEN-LAST:event_reportsButtonActionPerformed

    private void historyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyButtonActionPerformed
        mainFrame.showPanel("consultationHistory");
    }//GEN-LAST:event_historyButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        mainFrame.showPanel("clinicMenu");
    }//GEN-LAST:event_backButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton appointmentButton;
    private javax.swing.JButton backButton;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel buttonWrapper;
    private javax.swing.JPanel buttonWrapperPanel;
    private javax.swing.JButton consultationButton;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JButton prescriptionButton;
    private javax.swing.JButton queueButton;
    private javax.swing.JButton reportsButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables
}