package boundary.PharmacyManagementUI;

import adt.Pair;
import enitity.Medicine;
import javax.swing.*;
import utility.ImageUtils;

/**
 *
 * @author Lee Wan Ching
 */
public class MedicineAddDialog extends javax.swing.JDialog {

    private Pair<String, Medicine> result;

    /**
     * Creates new form MedicineDialog
     */
    public MedicineAddDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        logoLabel = ImageUtils.getImageLabel("tarumt_logo.png", logoLabel);

        String newId = "MED" + String.format("%03d", Medicine.getMedicineIndex() + 1);
        formMedIDfield.setText(newId);

        this.setLocationRelativeTo(parent);

        // Category options
        formCategoryBox.addItem("Select Category");
        formCategoryBox.addItem("Antibiotic");
        formCategoryBox.addItem("Analgesic");
        formCategoryBox.addItem("Antipyretic");
        formCategoryBox.addItem("Antihistamine");
        formCategoryBox.addItem("Antiviral");
        formCategoryBox.addItem("Antifungal");
        formCategoryBox.addItem("Antidepressant");
        formCategoryBox.addItem("Cardiovascular");
        formCategoryBox.addItem("Respiratory");
        formCategoryBox.addItem("Gastrointestinal");
        formCategoryBox.addItem("Dermatological");
        formCategoryBox.addItem("Vitamin / Supplement");
        formCategoryBox.addItem("Other");

        // Formulation options
        formFormulationBox.addItem("Select Formulation");
        formFormulationBox.addItem("Tablet");
        formFormulationBox.addItem("Capsule");
        formFormulationBox.addItem("Liquid");
        formFormulationBox.addItem("Syrup");
        formFormulationBox.addItem("Ointment");
        formFormulationBox.addItem("Cream");
        formFormulationBox.addItem("Gel");
        formFormulationBox.addItem("Injection");
        formFormulationBox.addItem("Inhaler");
        formFormulationBox.addItem("Drops");
        formFormulationBox.addItem("Suppository");
        formFormulationBox.addItem("Powder");
        formFormulationBox.addItem("Patch");
        formFormulationBox.addItem("Spray");
    }

    public Pair<String, Medicine> getResult() {
        return result;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoPanel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        titlePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        formWrapperPanel = new javax.swing.JPanel();
        formGridPanel = new javax.swing.JPanel();
        formMedIDlabel = new javax.swing.JLabel();
        formMedIDfield = new javax.swing.JTextField();
        formNameLabel = new javax.swing.JLabel();
        formNameInput = new javax.swing.JTextField();
        formBrandNameLabel = new javax.swing.JLabel();
        formBrandNameInput = new javax.swing.JTextField();
        formCategoryLabel = new javax.swing.JLabel();
        formCategoryBox = new javax.swing.JComboBox<>();
        formFormulationLabel = new javax.swing.JLabel();
        formFormulationBox = new javax.swing.JComboBox<>();
        formDosageLabel = new javax.swing.JLabel();
        formDosageInput = new javax.swing.JTextField();
        formQuantityLabel = new javax.swing.JLabel();
        formQuantityInput = new javax.swing.JTextField();
        formPriceLabel = new javax.swing.JLabel();
        formPriceInput = new javax.swing.JTextField();
        buttonPanel = new javax.swing.JPanel();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 640));
        setPreferredSize(new java.awt.Dimension(700, 640));

        logoPanel.setLayout(new java.awt.BorderLayout());
        logoPanel.add(logoLabel, java.awt.BorderLayout.CENTER);

        titlePanel.setLayout(new java.awt.BorderLayout());

        titleLabel.setFont(new java.awt.Font("Corbel", 1, 36)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("New Medicine Entry");
        titleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlePanel.add(titleLabel, java.awt.BorderLayout.PAGE_START);

        formGridPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Medicine Information :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Corbel", 1, 14))); // NOI18N
        formGridPanel.setMinimumSize(new java.awt.Dimension(400, 380));
        formGridPanel.setPreferredSize(new java.awt.Dimension(400, 380));
        formGridPanel.setLayout(new java.awt.GridLayout(8, 2, 5, 15));

        formMedIDlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formMedIDlabel.setText("ID :");
        formGridPanel.add(formMedIDlabel);

        formMedIDfield.setEditable(false);
        formMedIDfield.setColumns(15);
        formGridPanel.add(formMedIDfield);

        formNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formNameLabel.setText("Name :");
        formGridPanel.add(formNameLabel);

        formNameInput.setColumns(15);
        formGridPanel.add(formNameInput);

        formBrandNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formBrandNameLabel.setText("Brand Name :");
        formGridPanel.add(formBrandNameLabel);

        formBrandNameInput.setColumns(15);
        formGridPanel.add(formBrandNameInput);

        formCategoryLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formCategoryLabel.setText("Category : ");
        formGridPanel.add(formCategoryLabel);

        formCategoryBox.setPreferredSize(new java.awt.Dimension(100, 29));
        formGridPanel.add(formCategoryBox);

        formFormulationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formFormulationLabel.setText("Formulation : ");
        formGridPanel.add(formFormulationLabel);

        formFormulationBox.setPreferredSize(new java.awt.Dimension(100, 29));
        formGridPanel.add(formFormulationBox);

        formDosageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formDosageLabel.setText("Dosage : ");
        formGridPanel.add(formDosageLabel);

        formDosageInput.setColumns(15);
        formGridPanel.add(formDosageInput);

        formQuantityLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formQuantityLabel.setText("Quantity :");
        formGridPanel.add(formQuantityLabel);

        formQuantityInput.setColumns(15);
        formGridPanel.add(formQuantityInput);

        formPriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formPriceLabel.setText("Price (RM) :");
        formGridPanel.add(formPriceLabel);

        formPriceInput.setColumns(15);
        formGridPanel.add(formPriceInput);

        formWrapperPanel.add(formGridPanel);

        titlePanel.add(formWrapperPanel, java.awt.BorderLayout.CENTER);

        logoPanel.add(titlePanel, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(logoPanel, java.awt.BorderLayout.PAGE_START);

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(saveButton);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(cancelButton);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        try {
            String id = formMedIDfield.getText().trim();
            String name = formNameInput.getText().trim();
            String brand = formBrandNameInput.getText().trim();
            String category = (String) formCategoryBox.getSelectedItem();
            String formulation = (String) formFormulationBox.getSelectedItem();
            String dosage = formDosageInput.getText().trim();
            String quantityText = formQuantityInput.getText().trim();
            String priceText = formPriceInput.getText().trim();

            if (name.isEmpty()) {
                throw new IllegalArgumentException("Medicine Name cannot be empty.");
            }
            if (!name.matches("[a-zA-Z\\s]+")) {
                throw new IllegalArgumentException("Medicine Name cannot include numbers or special characters.");
            }

            if (brand.isEmpty()) {
                throw new IllegalArgumentException("Brand Name cannot be empty.");
            }
            if (!brand.matches("[a-zA-Z\\s]+")) {
                throw new IllegalArgumentException("Brand Name cannot include numbers or special characters.");
            }

            if (category == null || category.equals("Select Category")) {
                throw new IllegalArgumentException("Please select a valid Category.");
            }

            if (formulation == null || formulation.equals("Select Formulation")) {
                throw new IllegalArgumentException("Please select a valid Formulation.");
            }

            if (!dosage.isEmpty() && !dosage.matches("[a-zA-Z0-9\\s/]+")) {
                throw new IllegalArgumentException("Dosage contains invalid characters.");
            }

            int quantity;
            try {
                quantity = Integer.parseInt(quantityText);
                if (quantity < 0) {
                    throw new IllegalArgumentException("Quantity cannot be negative.");
                }
            } catch (NumberFormatException e) {
                throw new IllegalArgumentException("Quantity must be a valid integer.");
            }

            double price;
            try {
                price = Double.parseDouble(priceText);
                if (price < 0) {
                    throw new IllegalArgumentException("Price cannot be negative.");
                }
            } catch (NumberFormatException e) {
                throw new IllegalArgumentException("Price must be a valid number.");
            }

            Medicine newMed = new Medicine(id, name, brand, category, formulation, dosage, quantity, price);
            result = new Pair<>(id, newMed);

            Medicine.setMedicineIndex(Medicine.getMedicineIndex() + 1);

            dispose();

        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Input Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Unexpected error occurred.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.result = null;
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField formBrandNameInput;
    private javax.swing.JLabel formBrandNameLabel;
    private javax.swing.JComboBox<String> formCategoryBox;
    private javax.swing.JLabel formCategoryLabel;
    private javax.swing.JTextField formDosageInput;
    private javax.swing.JLabel formDosageLabel;
    private javax.swing.JComboBox<String> formFormulationBox;
    private javax.swing.JLabel formFormulationLabel;
    private javax.swing.JPanel formGridPanel;
    private javax.swing.JTextField formMedIDfield;
    private javax.swing.JLabel formMedIDlabel;
    private javax.swing.JTextField formNameInput;
    private javax.swing.JLabel formNameLabel;
    private javax.swing.JTextField formPriceInput;
    private javax.swing.JLabel formPriceLabel;
    private javax.swing.JTextField formQuantityInput;
    private javax.swing.JLabel formQuantityLabel;
    private javax.swing.JPanel formWrapperPanel;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables
}
