/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package boundary.PharmacyManagementUI;

import adt.DoublyLinkedList;
import adt.Pair;
import enitity.Medicine;
import javax.swing.*;
import utility.ImageUtils;

/**
 *
 * @author Lee Wan Ching
 */

public class MedicineDialog extends javax.swing.JDialog {
    
    private Pair<String, Medicine> result;

    /**
     * Creates new form MedicineDialog
     */
    public MedicineDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        logoLabel = ImageUtils.getImageLabel("tarumt_logo.png", logoLabel);
        
        // Generate new medicine ID
        String newId = "MED" + String.format("%03d", Medicine.getMedicineIndex() + 1);
        formMedIDfield.setText(newId);
        
        this.setLocationRelativeTo(parent);

        // Add some type options
        formTypeBox.addItem("Tablet");
        formTypeBox.addItem("Capsule");
        formTypeBox.addItem("Liquid");
        formTypeBox.addItem("Syrup");
        formTypeBox.addItem("Ointment");
        formTypeBox.addItem("Cream");
        formTypeBox.addItem("Gel");
        formTypeBox.addItem("Injection");
        formTypeBox.addItem("Inhaler");
        formTypeBox.addItem("Drops");
        formTypeBox.addItem("Suppository");
        formTypeBox.addItem("Powder");
        formTypeBox.addItem("Patch");
        formTypeBox.addItem("Spray");
    }
    
    public Pair<String, Medicine> getResult() {
        return result;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoPanel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        titlePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        formWrapperPanel = new javax.swing.JPanel();
        formGridPanel = new javax.swing.JPanel();
        formMedIDlabel = new javax.swing.JLabel();
        formMedIDfield = new javax.swing.JTextField();
        formNameLabel = new javax.swing.JLabel();
        formNameInput = new javax.swing.JTextField();
        formTypeLabel = new javax.swing.JLabel();
        formTypeBox = new javax.swing.JComboBox<>();
        formQuantityLabel = new javax.swing.JLabel();
        formQuantityInput = new javax.swing.JTextField();
        formPriceLabel = new javax.swing.JLabel();
        formPriceInput = new javax.swing.JTextField();
        buttonPanel = new javax.swing.JPanel();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 500));
        setPreferredSize(new java.awt.Dimension(600, 500));

        logoPanel.setLayout(new java.awt.BorderLayout());
        logoPanel.add(logoLabel, java.awt.BorderLayout.CENTER);

        titlePanel.setLayout(new java.awt.BorderLayout());

        titleLabel.setFont(new java.awt.Font("Corbel", 1, 36)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("New Medicine Entry");
        titleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlePanel.add(titleLabel, java.awt.BorderLayout.PAGE_START);

        formGridPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Medicine Information :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Corbel", 1, 14))); // NOI18N
        formGridPanel.setMinimumSize(new java.awt.Dimension(350, 228));
        formGridPanel.setPreferredSize(new java.awt.Dimension(300, 228));
        formGridPanel.setLayout(new java.awt.GridLayout(5, 2, 5, 15));

        formMedIDlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formMedIDlabel.setText("ID :");
        formGridPanel.add(formMedIDlabel);

        formMedIDfield.setEditable(false);
        formMedIDfield.setColumns(15);
        formGridPanel.add(formMedIDfield);

        formNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formNameLabel.setText("Name :");
        formGridPanel.add(formNameLabel);

        formNameInput.setColumns(15);
        formGridPanel.add(formNameInput);

        formTypeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formTypeLabel.setText("Type :");
        formGridPanel.add(formTypeLabel);

        formTypeBox.setPreferredSize(new java.awt.Dimension(100, 29));
        formGridPanel.add(formTypeBox);

        formQuantityLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formQuantityLabel.setText("Quantity :");
        formGridPanel.add(formQuantityLabel);

        formQuantityInput.setColumns(15);
        formGridPanel.add(formQuantityInput);

        formPriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formPriceLabel.setText("Price :");
        formGridPanel.add(formPriceLabel);

        formPriceInput.setColumns(15);
        formGridPanel.add(formPriceInput);

        formWrapperPanel.add(formGridPanel);

        titlePanel.add(formWrapperPanel, java.awt.BorderLayout.CENTER);

        logoPanel.add(titlePanel, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(logoPanel, java.awt.BorderLayout.PAGE_START);

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(saveButton);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(cancelButton);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        try {
            String id = formMedIDfield.getText().trim();
            String name = formNameInput.getText().trim();
            String type = (String) formTypeBox.getSelectedItem();
            int quantity = Integer.parseInt(formQuantityInput.getText().trim());
            double price = Double.parseDouble(formPriceInput.getText().trim());

            if (name.isEmpty() || type == null) {
                throw new IllegalArgumentException("Field cannot be empty.");
            }

            Medicine newMed = new Medicine(id, name, type, quantity, price);

            result = new Pair<>(id, newMed);

            // Increment index
            Medicine.setMedicineIndex(Medicine.getMedicineIndex() + 1);

            dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please check your input values.", "Input Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.result = null;
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel formGridPanel;
    private javax.swing.JTextField formMedIDfield;
    private javax.swing.JLabel formMedIDlabel;
    private javax.swing.JTextField formNameInput;
    private javax.swing.JLabel formNameLabel;
    private javax.swing.JTextField formPriceInput;
    private javax.swing.JLabel formPriceLabel;
    private javax.swing.JTextField formQuantityInput;
    private javax.swing.JLabel formQuantityLabel;
    private javax.swing.JComboBox<String> formTypeBox;
    private javax.swing.JLabel formTypeLabel;
    private javax.swing.JPanel formWrapperPanel;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables
}